import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'en' | 'ru' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

interface LanguageProviderProps {
  children: ReactNode
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.starterGuide': 'Starter Guide',
    'nav.reports': 'Reports',
    'nav.compliance': 'Compliance',
    'nav.customerTrust': 'Customer Trust',
    'nav.suppliers': 'Suppliers',
    'nav.assets': 'Assets',
    'nav.integrations': 'Integrations',
    'nav.incidents': 'Incidents',
    'nav.alerts': 'Alerts',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.users': 'Users',
    'nav.roles': 'Roles',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.loginLink': 'Sign in',
    'auth.registerLink': 'Sign up',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.severity': 'Severity',
    'common.time': 'Time',
    'common.name': 'Name',
    'common.role': 'Role',
    'common.permissions': 'Permissions',
    'common.createdAt': 'Created At',
    'common.lastLogin': 'Last Login',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.activeDefenses': 'Active Defenses',
    'dashboard.blockedThreats': 'Blocked Threats',
    'dashboard.systemUptime': 'System Uptime',
    'dashboard.pendingAlerts': 'Pending Alerts',
    'dashboard.threatsOverTime': 'Threats Over Time',
    'dashboard.threatTypes': 'Threat Types',
    'dashboard.recentIncidents': 'Recent Incidents',

    // Admin
    'admin.title': 'Administration',
    'admin.dashboard': 'Admin Dashboard',
    'admin.userManagement': 'User Management',
    'admin.roleManagement': 'Role Management',
    'admin.createUser': 'Create User',
    'admin.editUser': 'Edit User',
    'admin.deleteUser': 'Delete User',
    'admin.createRole': 'Create Role',
    'admin.editRole': 'Edit Role',
    'admin.deleteRole': 'Delete Role',

    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Language',
    'settings.english': 'English',
    'settings.russian': 'Russian',
    'settings.spanish': 'Spanish',

    // Messages
    'message.settingsSaved': 'Settings saved!',
    'message.userCreated': 'User created successfully',
    'message.userUpdated': 'User updated successfully',
    'message.userDeleted': 'User deleted successfully',
    'message.roleCreated': 'Role created successfully',
    'message.roleUpdated': 'Role updated successfully',
    'message.roleDeleted': 'Role deleted successfully',
    'message.confirmDelete': 'Are you sure you want to delete this item?',
    'message.operationFailed': 'Operation failed. Please try again.',

    // Customer Trust
    'customerTrust.title': 'Customer Trust',
    'customerTrust.exportExcel': 'Export Excel',
    'customerTrust.exportPdf': 'Export PDF',
    'customerTrust.backToDashboard': 'Back to Dashboard',
    'customerTrust.addCustomerTrust': 'Add Customer Trust',
    'customerTrust.categoriesAndFilters': 'Customer Trust Categories & Filters',
    'customerTrust.levelType': 'Level Type (Category)',
    'customerTrust.allCustomerTrust': 'All Customer Trust',
    'customerTrust.client': 'Client',
    'customerTrust.partner': 'Partner',
    'customerTrust.sector': 'Customer Trust Sector',
    'customerTrust.allTypes': 'All Types',
    'customerTrust.healthcare': 'Healthcare',
    'customerTrust.pharmaceutical': 'Pharmaceutical industry',
    'customerTrust.motor': 'Motor industry',
    'customerTrust.oil': 'Oil industry',
    'customerTrust.construction': 'Construction industry',
    'customerTrust.engineering': 'Engineering',
    'customerTrust.financial': 'Financial services',
    'customerTrust.standards': 'Standards',
    'customerTrust.allStandards': 'All Standards',
    'customerTrust.nis2': 'NIS 2',
    'customerTrust.socv2': 'SOC v2',
    'customerTrust.gdpr': 'GDPR',
    'customerTrust.dora': 'DORA',
    'customerTrust.complianceLevel': 'Compliance Level',
    'customerTrust.allLevels': 'All Levels',
    'customerTrust.high': 'High (>85%)',
    'customerTrust.medium': 'Medium (40-85%)',
    'customerTrust.low': 'Low (<40%)',
    'customerTrust.searchPlaceholder': 'Search by name or responsible person...',
    'customerTrust.customerTrustName': 'Customer Trust Name',
    'customerTrust.category': 'Category',
    'customerTrust.customerTrustSector': 'Customer Trust Sector',
    'customerTrust.assignedStandards': 'Assigned Standards',
    'customerTrust.compliancePercent': 'Compliance %',
    'customerTrust.lastAssessment': 'Last Assessment',
    'customerTrust.actions': 'Actions',
    'customerTrust.view': 'View',
    'customerTrust.edit': 'Edit',
    'customerTrust.remove': 'Remove',
    'customerTrust.removeCustomerTrust': 'Remove Customer Trust',
    'customerTrust.removeConfirm': 'Are you sure you want to remove "{name}"? This action cannot be undone.',
    'customerTrust.customerTrustNameField': 'Customer Trust Name',
    'customerTrust.categoryField': 'Category',
    'customerTrust.sectorField': 'Sector',
    'customerTrust.assignedStandardsField': 'Assigned Standards (comma-separated)',
    'customerTrust.compliancePercentField': 'Compliance %',
    'customerTrust.lastAssessmentField': 'Last Assessment',
    'customerTrust.responsiblePerson': 'Responsible Person',
    'customerTrust.email': 'Email',
    'customerTrust.website': 'Website',
    'customerTrust.standardsPlaceholder': 'NIS2, GDPR, SOCv2',

    // Assets
    'assets.title': 'Assets',
    'assets.exportExcel': 'Export Excel',
    'assets.exportPdf': 'Export PDF',
    'assets.backToDashboard': 'Back to Dashboard',
    'assets.addAsset': 'Add Asset',
    'assets.assetFilters': 'Asset Filters',
    'assets.assetType': 'Asset Type',
    'assets.allTypes': 'All Types',
    'assets.servers': 'Servers',
    'assets.cloudResources': 'Cloud Resources',
    'assets.networkDevices': 'Network Devices',
    'assets.applications': 'Applications',
    'assets.databases': 'Databases',
    'assets.iot': 'IoT',
    'assets.other': 'Other',
    'assets.environment': 'Environment',
    'assets.allEnvironments': 'All Environments',
    'assets.production': 'Production',
    'assets.staging': 'Staging',
    'assets.development': 'Development',
    'assets.test': 'Test',
    'assets.complianceStandards': 'Compliance / Standards',
    'assets.riskLevel': 'Risk Level',
    'assets.allRiskLevels': 'All Risk Levels',
    'assets.high': 'High',
    'assets.medium': 'Medium',
    'assets.low': 'Low',
    'assets.notAssessed': 'Not Assessed',
    'assets.ownerResponsible': 'Owner / Responsible',
    'assets.allOwners': 'All Owners',
    'assets.searchPlaceholder': 'Search by name or IP/URL...',
    'assets.assetName': 'Asset Name',
    'assets.assetType': 'Asset Type',
    'assets.environment': 'Environment',
    'assets.assignedStandards': 'Assigned Standards',
    'assets.compliancePercent': 'Compliance %',
    'assets.riskLevel': 'Risk Level',
    'assets.lastAssessmentScan': 'Last Assessment / Scan',
    'assets.ownerResponsible': 'Owner / Responsible',
    'assets.actions': 'Actions',
    'assets.scan': 'Scan',
    'assets.edit': 'Edit',
    'assets.remove': 'Remove',
    'assets.addAsset': 'Add Asset',
    'assets.editAsset': 'Edit Asset',
    'assets.removeAsset': 'Remove Asset',
    'assets.removeConfirm': 'Are you sure you want to remove "{name}"? This action cannot be undone.',
    'assets.assetNameField': 'Asset Name',
    'assets.assetTypeField': 'Asset Type',
    'assets.environmentField': 'Environment',
    'assets.assignedStandardsField': 'Assigned Standards (comma-separated)',
    'assets.compliancePercentField': 'Compliance %',
    'assets.riskLevelField': 'Risk Level',
    'assets.lastAssessmentField': 'Last Assessment',
    'assets.ownerResponsibleField': 'Owner / Responsible',
    'assets.descriptionNotes': 'Description / Notes',
    'assets.ipUrlLocation': 'IP / URL / Location',
    'assets.standardsPlaceholder': 'GDPR, NIS2, SOC2',
    'assets.ipUrlPlaceholder': '192.168.1.100 or example.com',
    'assets.updateAsset': 'Update Asset',

    // Compliance
    'compliance.title': 'Compliance',
    'compliance.exportExcel': 'Export Excel',
    'compliance.exportPdf': 'Export PDF',
    'compliance.backToDashboard': 'Back to Dashboard',
    'compliance.addComplianceRecord': 'Add Compliance Record',
    'compliance.checkedSystemsAssets': 'Checked Systems/Assets',
    'compliance.totalRecords': 'total records',
    'compliance.incidents': 'Incidents',
    'compliance.nonCompliant': 'non-compliant',
    'compliance.compliancePercent': 'Compliance %',
    'compliance.average': 'average',
    'compliance.riskDistribution': 'Risk Distribution',
    'compliance.complianceFilters': 'Compliance Filters',
    'compliance.standardRegulation': 'Standard / Regulation',
    'compliance.allStandards': 'All Standards',
    'compliance.gdpr': 'GDPR',
    'compliance.nis2': 'NIS2',
    'compliance.iso27001': 'ISO 27001',
    'compliance.soc2': 'SOC2',
    'compliance.pciDss': 'PCI DSS',
    'compliance.dora': 'DORA',
    'compliance.other': 'Other',
    'compliance.statusRiskLevel': 'Status / Risk Level',
    'compliance.allStatuses': 'All Statuses',
    'compliance.compliant': 'Compliant',
    'compliance.partial': 'Partial',
    'compliance.nonCompliant': 'Non-Compliant',
    'compliance.notAssessed': 'Not Assessed',
    'compliance.departmentOwner': 'Department / Owner',
    'compliance.allDepartments': 'All Departments',
    'compliance.itDepartment': 'IT Department',
    'compliance.securityTeam': 'Security Team',
    'compliance.operations': 'Operations',
    'compliance.finance': 'Finance',
    'compliance.riskManagement': 'Risk Management',
    'compliance.hr': 'HR',
    'compliance.legal': 'Legal',
    'compliance.assessmentDateRange': 'Assessment Date Range',
    'compliance.searchPlaceholder': 'Search by standard, department, or status...',
    'compliance.standardRegulation': 'Standard / Regulation',
    'compliance.departmentOwner': 'Department / Owner',
    'compliance.status': 'Status',
    'compliance.compliancePercent': 'Compliance %',
    'compliance.lastAssessmentDate': 'Last Assessment Date',
    'compliance.nextScheduledAssessment': 'Next Scheduled Assessment',
    'compliance.actions': 'Actions',
    'compliance.viewSummary': 'View Summary',
    'compliance.editRecord': 'Edit Record',
    'compliance.deleteRecord': 'Delete Record',
    'compliance.addComplianceRecord': 'Add Compliance Record',
    'compliance.editComplianceRecord': 'Edit Compliance Record',
    'compliance.deleteComplianceRecord': 'Delete Compliance Record',
    'compliance.deleteConfirm': 'Are you sure you want to delete the compliance record for "{standard}"? This action cannot be undone.',
    'compliance.standardRegulationField': 'Standard / Regulation',
    'compliance.departmentOwnerField': 'Department / Owner',
    'compliance.statusField': 'Status',
    'compliance.compliancePercentField': 'Compliance %',
    'compliance.lastAssessmentDateField': 'Last Assessment Date',
    'compliance.nextScheduledAssessmentField': 'Next Scheduled Assessment',
    'compliance.recommendationsNotes': 'Recommendations / Notes',
    'compliance.addRecord': 'Add Record',
    'compliance.updateRecord': 'Update Record',
    'compliance.delete': 'Delete',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.dashboard': 'Панель управления',
    'nav.starterGuide': 'Руководство',
    'nav.reports': 'Отчеты',
    'nav.compliance': 'Соответствие',
    'nav.customerTrust': 'Доверие клиентов',
    'nav.suppliers': 'Поставщики',
    'nav.assets': 'Активы',
    'nav.integrations': 'Интеграции',
    'nav.incidents': 'Инциденты',
    'nav.alerts': 'Оповещения',
    'nav.settings': 'Настройки',
    'nav.profile': 'Профиль',
    'nav.admin': 'Администрирование',
    'nav.users': 'Пользователи',
    'nav.roles': 'Роли',

    // Auth
    'auth.login': 'Вход',
    'auth.register': 'Регистрация',
    'auth.logout': 'Выход',
    'auth.username': 'Имя пользователя',
    'auth.password': 'Пароль',
    'auth.email': 'Email',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.loginButton': 'Войти',
    'auth.registerButton': 'Зарегистрироваться',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.loginLink': 'Войти',
    'auth.registerLink': 'Зарегистрироваться',

    // Common
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.create': 'Создать',
    'common.update': 'Обновить',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.actions': 'Действия',
    'common.status': 'Статус',
    'common.type': 'Тип',
    'common.severity': 'Важность',
    'common.time': 'Время',
    'common.name': 'Имя',
    'common.role': 'Роль',
    'common.permissions': 'Разрешения',
    'common.createdAt': 'Создан',
    'common.lastLogin': 'Последний вход',

    // Dashboard
    'dashboard.title': 'Панель управления',
    'dashboard.activeDefenses': 'Активные защиты',
    'dashboard.blockedThreats': 'Блокированные угрозы',
    'dashboard.systemUptime': 'Время работы системы',
    'dashboard.pendingAlerts': 'Ожидающие оповещения',
    'dashboard.threatsOverTime': 'Угрозы по времени',
    'dashboard.threatTypes': 'Типы угроз',
    'dashboard.recentIncidents': 'Последние инциденты',

    // Admin
    'admin.title': 'Администрирование',
    'admin.dashboard': 'Админ панель',
    'admin.userManagement': 'Управление пользователями',
    'admin.roleManagement': 'Управление ролями',
    'admin.createUser': 'Создать пользователя',
    'admin.editUser': 'Редактировать пользователя',
    'admin.deleteUser': 'Удалить пользователя',
    'admin.createRole': 'Создать роль',
    'admin.editRole': 'Редактировать роль',
    'admin.deleteRole': 'Удалить роль',

    // Settings
    'settings.title': 'Настройки',
    'settings.profile': 'Профиль',
    'settings.appearance': 'Внешний вид',
    'settings.notifications': 'Уведомления',
    'settings.theme': 'Тема',
    'settings.light': 'Светлая',
    'settings.dark': 'Темная',
    'settings.language': 'Язык',
    'settings.english': 'Английский',
    'settings.russian': 'Русский',
    'settings.spanish': 'Испанский',

    // Messages
    'message.settingsSaved': 'Настройки сохранены!',
    'message.userCreated': 'Пользователь успешно создан',
    'message.userUpdated': 'Пользователь успешно обновлен',
    'message.userDeleted': 'Пользователь успешно удален',
    'message.roleCreated': 'Роль успешно создана',
    'message.roleUpdated': 'Роль успешно обновлена',
    'message.roleDeleted': 'Роль успешно удалена',
    'message.confirmDelete': 'Вы уверены, что хотите удалить этот элемент?',
    'message.operationFailed': 'Операция не удалась. Попробуйте еще раз.',

    // Customer Trust
    'customerTrust.title': 'Доверие клиентов',
    'customerTrust.exportExcel': 'Экспорт Excel',
    'customerTrust.exportPdf': 'Экспорт PDF',
    'customerTrust.backToDashboard': 'Назад к панели',
    'customerTrust.addCustomerTrust': 'Добавить клиента',
    'customerTrust.categoriesAndFilters': 'Категории и фильтры клиентов',
    'customerTrust.levelType': 'Тип уровня (Категория)',
    'customerTrust.allCustomerTrust': 'Все клиенты',
    'customerTrust.client': 'Клиент',
    'customerTrust.partner': 'Партнер',
    'customerTrust.sector': 'Сектор клиента',
    'customerTrust.allTypes': 'Все типы',
    'customerTrust.healthcare': 'Здравоохранение',
    'customerTrust.pharmaceutical': 'Фармацевтическая промышленность',
    'customerTrust.motor': 'Автомобильная промышленность',
    'customerTrust.oil': 'Нефтяная промышленность',
    'customerTrust.construction': 'Строительная промышленность',
    'customerTrust.engineering': 'Инженерия',
    'customerTrust.financial': 'Финансовые услуги',
    'customerTrust.standards': 'Стандарты',
    'customerTrust.allStandards': 'Все стандарты',
    'customerTrust.nis2': 'NIS 2',
    'customerTrust.socv2': 'SOC v2',
    'customerTrust.gdpr': 'GDPR',
    'customerTrust.dora': 'DORA',
    'customerTrust.complianceLevel': 'Уровень соответствия',
    'customerTrust.allLevels': 'Все уровни',
    'customerTrust.high': 'Высокий (>85%)',
    'customerTrust.medium': 'Средний (40-85%)',
    'customerTrust.low': 'Низкий (<40%)',
    'customerTrust.searchPlaceholder': 'Поиск по имени или ответственному лицу...',
    'customerTrust.customerTrustName': 'Имя клиента',
    'customerTrust.category': 'Категория',
    'customerTrust.customerTrustSector': 'Сектор клиента',
    'customerTrust.assignedStandards': 'Назначенные стандарты',
    'customerTrust.compliancePercent': 'Соответствие %',
    'customerTrust.lastAssessment': 'Последняя оценка',
    'customerTrust.actions': 'Действия',
    'customerTrust.view': 'Просмотр',
    'customerTrust.edit': 'Редактировать',
    'customerTrust.remove': 'Удалить',
    'customerTrust.removeCustomerTrust': 'Удалить клиента',
    'customerTrust.removeConfirm': 'Вы уверены, что хотите удалить "{name}"? Это действие нельзя отменить.',
    'customerTrust.customerTrustNameField': 'Имя клиента',
    'customerTrust.categoryField': 'Категория',
    'customerTrust.sectorField': 'Сектор',
    'customerTrust.assignedStandardsField': 'Назначенные стандарты (через запятую)',
    'customerTrust.compliancePercentField': 'Соответствие %',
    'customerTrust.lastAssessmentField': 'Последняя оценка',
    'customerTrust.responsiblePerson': 'Ответственное лицо',
    'customerTrust.email': 'Email',
    'customerTrust.website': 'Веб-сайт',
    'customerTrust.standardsPlaceholder': 'NIS2, GDPR, SOCv2',

    // Assets
    'assets.title': 'Активы',
    'assets.exportExcel': 'Экспорт Excel',
    'assets.exportPdf': 'Экспорт PDF',
    'assets.backToDashboard': 'Назад к панели',
    'assets.addAsset': 'Добавить актив',
    'assets.assetFilters': 'Фильтры активов',
    'assets.assetType': 'Тип актива',
    'assets.allTypes': 'Все типы',
    'assets.servers': 'Серверы',
    'assets.cloudResources': 'Облачные ресурсы',
    'assets.networkDevices': 'Сетевые устройства',
    'assets.applications': 'Приложения',
    'assets.databases': 'Базы данных',
    'assets.iot': 'IoT',
    'assets.other': 'Другое',
    'assets.environment': 'Окружение',
    'assets.allEnvironments': 'Все окружения',
    'assets.production': 'Продакшн',
    'assets.staging': 'Стейджинг',
    'assets.development': 'Разработка',
    'assets.test': 'Тест',
    'assets.complianceStandards': 'Соответствие / Стандарты',
    'assets.riskLevel': 'Уровень риска',
    'assets.allRiskLevels': 'Все уровни риска',
    'assets.high': 'Высокий',
    'assets.medium': 'Средний',
    'assets.low': 'Низкий',
    'assets.notAssessed': 'Не оценен',
    'assets.ownerResponsible': 'Владелец / Ответственный',
    'assets.allOwners': 'Все владельцы',
    'assets.searchPlaceholder': 'Поиск по имени или IP/URL...',
    'assets.assetName': 'Имя актива',
    'assets.assetType': 'Тип актива',
    'assets.environment': 'Окружение',
    'assets.assignedStandards': 'Назначенные стандарты',
    'assets.compliancePercent': 'Соответствие %',
    'assets.riskLevel': 'Уровень риска',
    'assets.lastAssessmentScan': 'Последняя оценка / Сканирование',
    'assets.ownerResponsible': 'Владелец / Ответственный',
    'assets.actions': 'Действия',
    'assets.scan': 'Сканировать',
    'assets.edit': 'Редактировать',
    'assets.remove': 'Удалить',
    'assets.addAsset': 'Добавить актив',
    'assets.editAsset': 'Редактировать актив',
    'assets.removeAsset': 'Удалить актив',
    'assets.removeConfirm': 'Вы уверены, что хотите удалить "{name}"? Это действие нельзя отменить.',
    'assets.assetNameField': 'Имя актива',
    'assets.assetTypeField': 'Тип актива',
    'assets.environmentField': 'Окружение',
    'assets.assignedStandardsField': 'Назначенные стандарты (через запятую)',
    'assets.compliancePercentField': 'Соответствие %',
    'assets.riskLevelField': 'Уровень риска',
    'assets.lastAssessmentField': 'Последняя оценка',
    'assets.ownerResponsibleField': 'Владелец / Ответственный',
    'assets.descriptionNotes': 'Описание / Заметки',
    'assets.ipUrlLocation': 'IP / URL / Местоположение',
    'assets.standardsPlaceholder': 'GDPR, NIS2, SOC2',
    'assets.ipUrlPlaceholder': '192.168.1.100 или example.com',
    'assets.updateAsset': 'Обновить актив',

    // Compliance
    'compliance.title': 'Соответствие',
    'compliance.exportExcel': 'Экспорт Excel',
    'compliance.exportPdf': 'Экспорт PDF',
    'compliance.backToDashboard': 'Назад к панели',
    'compliance.addComplianceRecord': 'Добавить запись соответствия',
    'compliance.checkedSystemsAssets': 'Проверенные системы/Активы',
    'compliance.totalRecords': 'всего записей',
    'compliance.incidents': 'Инциденты',
    'compliance.nonCompliant': 'несоответствующие',
    'compliance.compliancePercent': 'Соответствие %',
    'compliance.average': 'среднее',
    'compliance.riskDistribution': 'Распределение рисков',
    'compliance.complianceFilters': 'Фильтры соответствия',
    'compliance.standardRegulation': 'Стандарт / Регулирование',
    'compliance.allStandards': 'Все стандарты',
    'compliance.gdpr': 'GDPR',
    'compliance.nis2': 'NIS2',
    'compliance.iso27001': 'ISO 27001',
    'compliance.soc2': 'SOC2',
    'compliance.pciDss': 'PCI DSS',
    'compliance.dora': 'DORA',
    'compliance.other': 'Другое',
    'compliance.statusRiskLevel': 'Статус / Уровень риска',
    'compliance.allStatuses': 'Все статусы',
    'compliance.compliant': 'Соответствует',
    'compliance.partial': 'Частично',
    'compliance.nonCompliant': 'Не соответствует',
    'compliance.notAssessed': 'Не оценено',
    'compliance.departmentOwner': 'Отдел / Владелец',
    'compliance.allDepartments': 'Все отделы',
    'compliance.itDepartment': 'IT отдел',
    'compliance.securityTeam': 'Команда безопасности',
    'compliance.operations': 'Операции',
    'compliance.finance': 'Финансы',
    'compliance.riskManagement': 'Управление рисками',
    'compliance.hr': 'HR',
    'compliance.legal': 'Юридический',
    'compliance.assessmentDateRange': 'Диапазон дат оценки',
    'compliance.searchPlaceholder': 'Поиск по стандарту, отделу или статусу...',
    'compliance.standardRegulation': 'Стандарт / Регулирование',
    'compliance.departmentOwner': 'Отдел / Владелец',
    'compliance.status': 'Статус',
    'compliance.compliancePercent': 'Соответствие %',
    'compliance.lastAssessmentDate': 'Дата последней оценки',
    'compliance.nextScheduledAssessment': 'Следующая запланированная оценка',
    'compliance.actions': 'Действия',
    'compliance.viewSummary': 'Просмотр сводки',
    'compliance.editRecord': 'Редактировать запись',
    'compliance.deleteRecord': 'Удалить запись',
    'compliance.addComplianceRecord': 'Добавить запись соответствия',
    'compliance.editComplianceRecord': 'Редактировать запись соответствия',
    'compliance.deleteComplianceRecord': 'Удалить запись соответствия',
    'compliance.deleteConfirm': 'Вы уверены, что хотите удалить запись соответствия для "{standard}"? Это действие нельзя отменить.',
    'compliance.standardRegulationField': 'Стандарт / Регулирование',
    'compliance.departmentOwnerField': 'Отдел / Владелец',
    'compliance.statusField': 'Статус',
    'compliance.compliancePercentField': 'Соответствие %',
    'compliance.lastAssessmentDateField': 'Дата последней оценки',
    'compliance.nextScheduledAssessmentField': 'Следующая запланированная оценка',
    'compliance.recommendationsNotes': 'Рекомендации / Заметки',
    'compliance.addRecord': 'Добавить запись',
    'compliance.updateRecord': 'Обновить запись',
    'compliance.delete': 'Удалить',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel de control',
    'nav.starterGuide': 'Guía de inicio',
    'nav.reports': 'Informes',
    'nav.compliance': 'Cumplimiento',
    'nav.customerTrust': 'Confianza del cliente',
    'nav.suppliers': 'Proveedores',
    'nav.assets': 'Activos',
    'nav.integrations': 'Integraciones',
    'nav.incidents': 'Incidentes',
    'nav.alerts': 'Alertas',
    'nav.settings': 'Configuración',
    'nav.profile': 'Perfil',
    'nav.admin': 'Administración',
    'nav.users': 'Usuarios',
    'nav.roles': 'Roles',

    // Auth
    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.logout': 'Cerrar sesión',
    'auth.username': 'Nombre de usuario',
    'auth.password': 'Contraseña',
    'auth.email': 'Email',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.loginButton': 'Iniciar sesión',
    'auth.registerButton': 'Registrarse',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.loginLink': 'Iniciar sesión',
    'auth.registerLink': 'Registrarse',

    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.actions': 'Acciones',
    'common.status': 'Estado',
    'common.type': 'Tipo',
    'common.severity': 'Severidad',
    'common.time': 'Tiempo',
    'common.name': 'Nombre',
    'common.role': 'Rol',
    'common.permissions': 'Permisos',
    'common.createdAt': 'Creado en',
    'common.lastLogin': 'Último acceso',

    // Dashboard
    'dashboard.title': 'Panel de control',
    'dashboard.activeDefenses': 'Defensas activas',
    'dashboard.blockedThreats': 'Amenazas bloqueadas',
    'dashboard.systemUptime': 'Tiempo de actividad del sistema',
    'dashboard.pendingAlerts': 'Alertas pendientes',
    'dashboard.threatsOverTime': 'Amenazas a lo largo del tiempo',
    'dashboard.threatTypes': 'Tipos de amenazas',
    'dashboard.recentIncidents': 'Incidentes recientes',

    // Admin
    'admin.title': 'Administración',
    'admin.dashboard': 'Panel de administración',
    'admin.userManagement': 'Gestión de usuarios',
    'admin.roleManagement': 'Gestión de roles',
    'admin.createUser': 'Crear usuario',
    'admin.editUser': 'Editar usuario',
    'admin.deleteUser': 'Eliminar usuario',
    'admin.createRole': 'Crear rol',
    'admin.editRole': 'Editar rol',
    'admin.deleteRole': 'Eliminar rol',

    // Settings
    'settings.title': 'Configuración',
    'settings.profile': 'Perfil',
    'settings.appearance': 'Apariencia',
    'settings.notifications': 'Notificaciones',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.language': 'Idioma',
    'settings.english': 'Inglés',
    'settings.russian': 'Ruso',
    'settings.spanish': 'Español',

    // Messages
    'message.settingsSaved': '¡Configuración guardada!',
    'message.userCreated': 'Usuario creado exitosamente',
    'message.userUpdated': 'Usuario actualizado exitosamente',
    'message.userDeleted': 'Usuario eliminado exitosamente',
    'message.roleCreated': 'Rol creado exitosamente',
    'message.roleUpdated': 'Rol actualizado exitosamente',
    'message.roleDeleted': 'Rol eliminado exitosamente',
    'message.confirmDelete': '¿Estás seguro de que quieres eliminar este elemento?',
    'message.operationFailed': 'La operación falló. Inténtalo de nuevo.',

    // Customer Trust
    'customerTrust.title': 'Confianza del Cliente',
    'customerTrust.exportExcel': 'Exportar Excel',
    'customerTrust.exportPdf': 'Exportar PDF',
    'customerTrust.backToDashboard': 'Volver al Panel',
    'customerTrust.addCustomerTrust': 'Agregar Cliente',
    'customerTrust.categoriesAndFilters': 'Categorías y Filtros de Clientes',
    'customerTrust.levelType': 'Tipo de Nivel (Categoría)',
    'customerTrust.allCustomerTrust': 'Todos los Clientes',
    'customerTrust.client': 'Cliente',
    'customerTrust.partner': 'Socio',
    'customerTrust.sector': 'Sector del Cliente',
    'customerTrust.allTypes': 'Todos los Tipos',
    'customerTrust.healthcare': 'Salud',
    'customerTrust.pharmaceutical': 'Industria farmacéutica',
    'customerTrust.motor': 'Industria automotriz',
    'customerTrust.oil': 'Industria petrolera',
    'customerTrust.construction': 'Industria de la construcción',
    'customerTrust.engineering': 'Ingeniería',
    'customerTrust.financial': 'Servicios financieros',
    'customerTrust.standards': 'Estándares',
    'customerTrust.allStandards': 'Todos los Estándares',
    'customerTrust.nis2': 'NIS 2',
    'customerTrust.socv2': 'SOC v2',
    'customerTrust.gdpr': 'GDPR',
    'customerTrust.dora': 'DORA',
    'customerTrust.complianceLevel': 'Nivel de Cumplimiento',
    'customerTrust.allLevels': 'Todos los Niveles',
    'customerTrust.high': 'Alto (>85%)',
    'customerTrust.medium': 'Medio (40-85%)',
    'customerTrust.low': 'Bajo (<40%)',
    'customerTrust.searchPlaceholder': 'Buscar por nombre o persona responsable...',
    'customerTrust.customerTrustName': 'Nombre del Cliente',
    'customerTrust.category': 'Categoría',
    'customerTrust.customerTrustSector': 'Sector del Cliente',
    'customerTrust.assignedStandards': 'Estándares Asignados',
    'customerTrust.compliancePercent': 'Cumplimiento %',
    'customerTrust.lastAssessment': 'Última Evaluación',
    'customerTrust.actions': 'Acciones',
    'customerTrust.view': 'Ver',
    'customerTrust.edit': 'Editar',
    'customerTrust.remove': 'Eliminar',
    'customerTrust.removeCustomerTrust': 'Eliminar Cliente',
    'customerTrust.removeConfirm': '¿Estás seguro de que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
    'customerTrust.customerTrustNameField': 'Nombre del Cliente',
    'customerTrust.categoryField': 'Categoría',
    'customerTrust.sectorField': 'Sector',
    'customerTrust.assignedStandardsField': 'Estándares Asignados (separados por comas)',
    'customerTrust.compliancePercentField': 'Cumplimiento %',
    'customerTrust.lastAssessmentField': 'Última Evaluación',
    'customerTrust.responsiblePerson': 'Persona Responsable',
    'customerTrust.email': 'Email',
    'customerTrust.website': 'Sitio Web',
    'customerTrust.standardsPlaceholder': 'NIS2, GDPR, SOCv2',

    // Assets
    'assets.title': 'Activos',
    'assets.exportExcel': 'Exportar Excel',
    'assets.exportPdf': 'Exportar PDF',
    'assets.backToDashboard': 'Volver al Panel',
    'assets.addAsset': 'Agregar Activo',
    'assets.assetFilters': 'Filtros de Activos',
    'assets.assetType': 'Tipo de Activo',
    'assets.allTypes': 'Todos los Tipos',
    'assets.servers': 'Servidores',
    'assets.cloudResources': 'Recursos en la Nube',
    'assets.networkDevices': 'Dispositivos de Red',
    'assets.applications': 'Aplicaciones',
    'assets.databases': 'Bases de Datos',
    'assets.iot': 'IoT',
    'assets.other': 'Otro',
    'assets.environment': 'Entorno',
    'assets.allEnvironments': 'Todos los Entornos',
    'assets.production': 'Producción',
    'assets.staging': 'Staging',
    'assets.development': 'Desarrollo',
    'assets.test': 'Prueba',
    'assets.complianceStandards': 'Cumplimiento / Estándares',
    'assets.riskLevel': 'Nivel de Riesgo',
    'assets.allRiskLevels': 'Todos los Niveles de Riesgo',
    'assets.high': 'Alto',
    'assets.medium': 'Medio',
    'assets.low': 'Bajo',
    'assets.notAssessed': 'No Evaluado',
    'assets.ownerResponsible': 'Propietario / Responsable',
    'assets.allOwners': 'Todos los Propietarios',
    'assets.searchPlaceholder': 'Buscar por nombre o IP/URL...',
    'assets.assetName': 'Nombre del Activo',
    'assets.assetType': 'Tipo de Activo',
    'assets.environment': 'Entorno',
    'assets.assignedStandards': 'Estándares Asignados',
    'assets.compliancePercent': 'Cumplimiento %',
    'assets.riskLevel': 'Nivel de Riesgo',
    'assets.lastAssessmentScan': 'Última Evaluación / Escaneo',
    'assets.ownerResponsible': 'Propietario / Responsable',
    'assets.actions': 'Acciones',
    'assets.scan': 'Escanear',
    'assets.edit': 'Editar',
    'assets.remove': 'Eliminar',
    'assets.addAsset': 'Agregar Activo',
    'assets.editAsset': 'Editar Activo',
    'assets.removeAsset': 'Eliminar Activo',
    'assets.removeConfirm': '¿Estás seguro de que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
    'assets.assetNameField': 'Nombre del Activo',
    'assets.assetTypeField': 'Tipo de Activo',
    'assets.environmentField': 'Entorno',
    'assets.assignedStandardsField': 'Estándares Asignados (separados por comas)',
    'assets.compliancePercentField': 'Cumplimiento %',
    'assets.riskLevelField': 'Nivel de Riesgo',
    'assets.lastAssessmentField': 'Última Evaluación',
    'assets.ownerResponsibleField': 'Propietario / Responsable',
    'assets.descriptionNotes': 'Descripción / Notas',
    'assets.ipUrlLocation': 'IP / URL / Ubicación',
    'assets.standardsPlaceholder': 'GDPR, NIS2, SOC2',
    'assets.ipUrlPlaceholder': '192.168.1.100 o example.com',
    'assets.updateAsset': 'Actualizar Activo',

    // Compliance
    'compliance.title': 'Cumplimiento',
    'compliance.exportExcel': 'Exportar Excel',
    'compliance.exportPdf': 'Exportar PDF',
    'compliance.backToDashboard': 'Volver al Panel',
    'compliance.addComplianceRecord': 'Agregar Registro de Cumplimiento',
    'compliance.checkedSystemsAssets': 'Sistemas/Activos Verificados',
    'compliance.totalRecords': 'registros totales',
    'compliance.incidents': 'Incidentes',
    'compliance.nonCompliant': 'no conformes',
    'compliance.compliancePercent': 'Cumplimiento %',
    'compliance.average': 'promedio',
    'compliance.riskDistribution': 'Distribución de Riesgos',
    'compliance.complianceFilters': 'Filtros de Cumplimiento',
    'compliance.standardRegulation': 'Estándar / Regulación',
    'compliance.allStandards': 'Todos los Estándares',
    'compliance.gdpr': 'GDPR',
    'compliance.nis2': 'NIS2',
    'compliance.iso27001': 'ISO 27001',
    'compliance.soc2': 'SOC2',
    'compliance.pciDss': 'PCI DSS',
    'compliance.dora': 'DORA',
    'compliance.other': 'Otro',
    'compliance.statusRiskLevel': 'Estado / Nivel de Riesgo',
    'compliance.allStatuses': 'Todos los Estados',
    'compliance.compliant': 'Conforme',
    'compliance.partial': 'Parcial',
    'compliance.nonCompliant': 'No Conforme',
    'compliance.notAssessed': 'No Evaluado',
    'compliance.departmentOwner': 'Departamento / Propietario',
    'compliance.allDepartments': 'Todos los Departamentos',
    'compliance.itDepartment': 'Departamento de TI',
    'compliance.securityTeam': 'Equipo de Seguridad',
    'compliance.operations': 'Operaciones',
    'compliance.finance': 'Finanzas',
    'compliance.riskManagement': 'Gestión de Riesgos',
    'compliance.hr': 'RRHH',
    'compliance.legal': 'Legal',
    'compliance.assessmentDateRange': 'Rango de Fechas de Evaluación',
    'compliance.searchPlaceholder': 'Buscar por estándar, departamento o estado...',
    'compliance.standardRegulation': 'Estándar / Regulación',
    'compliance.departmentOwner': 'Departamento / Propietario',
    'compliance.status': 'Estado',
    'compliance.compliancePercent': 'Cumplimiento %',
    'compliance.lastAssessmentDate': 'Fecha de Última Evaluación',
    'compliance.nextScheduledAssessment': 'Próxima Evaluación Programada',
    'compliance.actions': 'Acciones',
    'compliance.viewSummary': 'Ver Resumen',
    'compliance.editRecord': 'Editar Registro',
    'compliance.deleteRecord': 'Eliminar Registro',
    'compliance.addComplianceRecord': 'Agregar Registro de Cumplimiento',
    'compliance.editComplianceRecord': 'Editar Registro de Cumplimiento',
    'compliance.deleteComplianceRecord': 'Eliminar Registro de Cumplimiento',
    'compliance.deleteConfirm': '¿Estás seguro de que quieres eliminar el registro de cumplimiento para "{standard}"? Esta acción no se puede deshacer.',
    'compliance.standardRegulationField': 'Estándar / Regulación',
    'compliance.departmentOwnerField': 'Departamento / Propietario',
    'compliance.statusField': 'Estado',
    'compliance.compliancePercentField': 'Cumplimiento %',
    'compliance.lastAssessmentDateField': 'Fecha de Última Evaluación',
    'compliance.nextScheduledAssessmentField': 'Próxima Evaluación Programada',
    'compliance.recommendationsNotes': 'Recomendaciones / Notas',
    'compliance.addRecord': 'Agregar Registro',
    'compliance.updateRecord': 'Actualizar Registro',
    'compliance.delete': 'Eliminar',
  }
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language
    return saved && ['en', 'ru', 'es'].includes(saved) ? saved : 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}